language: cpp

matrix:
    include:
        - compiler: clang
          env: BUILD_TYPE=Debug
        - compiler: clang
          env: BUILD_TYPE=Release
        - compiler: gcc
          env: BUILD_TYPE=Debug
        - compiler: gcc
          env: BUILD_TYPE=Release

install:
  - git submodule update --init
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ..
  - make
  - make test
  - travis_wait 120 ./db_benchmark2
addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - cmake-data
      - gcc-4.8
      - g++-4.8
      - clang

notifications:
  email: false

sudo: required